sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 8.0  # Atualizado para .NET 8.0
services: docker

before_install:
  # Adiciona swap para evitar erro de falta de memória (OOM)
  - sudo swapoff -a
  - sudo dd if=/dev/zero of=/swapfile bs=1M count=4096
  - sudo mkswap /swapfile
  - sudo swapon /swapfile
  - cd .
  - echo "We are in the right folder!"

script:
  # Build Docker usando o docker-compose
  - docker-compose build

before_deploy:
  # Login no DockerHub antes do deploy
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script:
    # Tag para as imagens antes de enviá-las para o DockerHub
    docker tag rest-with-asp-net:latest $DOCKER_USERNAME/rest-with-asp-net:$TRAVIS_JOB_ID;
    docker tag rest-with-asp-net-db:latest $DOCKER_USERNAME/rest-with-asp-net-db:$TRAVIS_JOB_ID;
    # Push das imagens para o DockerHub
    docker push $DOCKER_USERNAME/rest-with-asp-net:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/rest-with-asp-net-db:$TRAVIS_JOB_ID;
  on:
    branch: main

notifications:
  email: false
