sudo: required
dist: focal
language: generic
mono: none
services:
  - docker

cache:
  directories:
    - $HOME/.nuget/packages
    - $HOME/.local/share/NuGet/v3-cache

before_install:
  - cd .
  - echo "We are in the right folder!"
  - sudo apt-get update
  - sudo apt-get install -y apt-transport-https
  - sudo snap install dotnet-sdk --classic --channel 8.0/stable
  - dotnet restore "./Project/RestWithASPNET.csproj"

script:
  - cd ./Project
  - docker build --no-cache -t rest-with-asp-net:latest .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script:
    - docker tag rest-with-asp-net:latest $DOCKER_USERNAME/rest-with-asp-net:$TRAVIS_JOB_ID
    - docker tag rest-with-asp-net-db:latest $DOCKER_USERNAME/rest-with-asp-net-db:$TRAVIS_JOB_ID
    - docker push $DOCKER_USERNAME/rest-with-asp-net:$TRAVIS_JOB_ID
    - docker push $DOCKER_USERNAME/rest-with-asp-net-db:$TRAVIS_JOB_ID
  on:
    branch: main

notifications:
  email: false
