sudo: required
dist: focal
language: generic
mono: none
services:
  - docker

cache:
  directories:
    - $HOME/.nuget/packages
    - $HOME/.local/share/NuGet/v3-cache

before_install:
  - cd .
  - echo "We are in the right folder!"
  - sudo apt-get update
  - sudo apt-get install -y apt-transport-https
  - sudo snap install dotnet-sdk --classic --channel 8.0/stable
  - dotnet restore "./Project/RestWithASPNET.csproj"

script:
  - cd ./Project
  - docker build --no-cache -t rest-with-asp-net:latest .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - git checkout main 
  - docker tag rest-with-asp-net:latest $DOCKER_USERNAME/rest-with-asp-net:latest-$(date +%s)
  - docker push $DOCKER_USERNAME/rest-with-asp-net:latest-$(date +%s)

deploy:
  provider: script
  script:
    - echo "Deployed"  
  on:
    branch: main

notifications:
  email: false
