version: '3.4'

services:
  db:
    image: rest-with-asp-net-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_asp_net
    ports:
      - 3308:3306
    networks: 
      - udemy-network
      
  rest-with-asp-net:
    image: rest-with-asp-net
    build:
      context: .
      dockerfile: Project/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 4430:8080
    depends_on:
      - db
    networks: 
      - udemy-network

networks:
  udemy-network:
    driver: bridge
